FROM php:8.2-cli

WORKDIR /var/www

RUN apt-get update \ 
    && apt-get install libzip-dev -y \
    && docker-php-ext-install zip

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \ 
    && php -r "unlink('composer-setup.php');"

RUN php composer.phar create-project laravel/laravel app

ENTRYPOINT [ "php", "app/artisan", "serve" ]
CMD [ "--host=0.0.0.0" ]
